[project]
name = 'Reality-Simulation-Insurance-Protocol'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.consciousness-boundary-monitor]
path = 'contracts/consciousness-boundary-monitor.clar'
clarity_version = 3
epoch = '3.2'

[contracts.simulation-failure-claims]
path = 'contracts/simulation-failure-claims.clar'
clarity_version = 3
epoch = 'latest'

[contracts.simulation-integrity-oracle]
path = 'contracts/simulation-integrity-oracle.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
